name: Azure

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed
      
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: print
        run: echo hi!
