on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # create the release
  build:
    name: Build and Push version branch
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: get release tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: git
        run: |
          echo ${{ steps.vars.outputs.tag }}
          git config --global user.email "ben@h2clipper.com"
          git config --global user.name "Github Action"
          git checkout -b Release-${{ steps.vars.outputs.tag }}
          sed -i "release: ${{ steps.vars.outputs.tag }}" default.cfg
          git add .
          git commit -m "Release ${{ steps.vars.outputs.tag }}"
          git push origin Release-${{ steps.vars.outputs.tag }}
        
