on:
  push:
    branches:
      main

jobs:
  # create the release
  write-version:
    name: "Update Version"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ steps.get-latest-tag.outputs.tag }}'
          sha: '${{ github.event.pull_request.head.sha }}'
