on:
  push:
    branches:
      main

jobs:
  # create the release
  build:
    name: "Build and Push version branch"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - name: git
        run: |
          git checkout -b '${{ steps.get-latest-tag.outputs.tag }}'
          git describe --tags --abbrev=0 > version.txt
          git add .
          git commit -m "${{ steps.get-latest-tag.outputs.tag }}"
          git push origin ${{ steps.get-latest-tag.outputs.tag }}
        