on:
  push:
    branches:
      main

jobs:
  # create the release
  build:
    name: "Build and Push version branch"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "get release tag"
        run: |
          export RELEASE_TAG=$(git describe --tags --abbrev=0)
          echo "The release tag is $RELEASE_TAG"

      - name: git
        run: |
          git checkout -b $RELEASE_TAG
          git describe --tags --abbrev=0 > version.txt
          git add .
          git commit -m "${{ steps.get-latest-tag.outputs.tag }}"
          git push origin $RELEASE_TAG
        