on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # create the release
  build:
    name: Build and Push version branch
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: get release tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: git
        run: |
          echo ${{ steps.vars.outputs.tag }}
          git checkout -b ${{ steps.vars.outputs.tag }}
          git describe --tags --abbrev=0 > version.txt
          git add .
          git commit -m "${{ steps.vars.outputs.tag }}"
          git push origin ${{ steps.vars.outputs.tag }}
        
