on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # create the release
  build:
    name: Build and Push version branch
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: get release tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: create release branch
        run: |
          echo ${{ steps.vars.outputs.tag }}
          git config --global user.email "ben@h2clipper.com"
          git config --global user.name "Github Action"
          git checkout -b release-${{ steps.vars.outputs.tag }}
          
      - name: write release tag to configuration file
        env:
          RELEASE_TEXT: "release: ${{ steps.vars.outputs.tag }}"
        run: |
          sed -i '1s/.*/${{ env.RELEASE_TEXT }}/' default.cfg
          
      - name: push to release branch
        run: |
          git add .
          git commit -m "Release ${{ steps.vars.outputs.tag }}"
          git push origin release-${{ steps.vars.outputs.tag }}
      
      - name: get commit id
        id: commit_id
        run: echo ::set-output name=tag::$(git log -n 1 --pretty=format:"%H")
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ steps.commit_id.outputs.tag }}
          generateReleaseNotes: true
